/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MERGE_H_RPCGEN
#define _MERGE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct merge {
	char listA[10];
	char listB[10];
};
typedef struct merge merge;

#define MERGE 0x23111111
#define MERGE_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define MERGE 1
extern  int * merge_1(merge *, CLIENT *);
extern  int * merge_1_svc(merge *, struct svc_req *);
extern int merge_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MERGE 1
extern  int * merge_1();
extern  int * merge_1_svc();
extern int merge_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_merge (XDR *, merge*);

#else /* K&R C */
extern bool_t xdr_merge ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MERGE_H_RPCGEN */
