/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "merge.h"

int *
merge_1_svc(merge *argp, struct svc_req *rqstp)
{
	static int result[10];
	printf("[Server] Merge Function Called");
	size_t n=size_t(argp->listA)/size_t(argp->listA[0]);
	size_t m=size_t(argp->listB)/size_t(argp->listB[0]);
	int i=0;
	for(i=0;i<n;i++){
		result[i]=(int)argp->listA[i];
	}
	for(i=0;i<m;i++){
		result[i+n]=(int)argp->listA[i];
	}
	return &result;
}
