/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "merge.h"

bool_t
xdr_merge (XDR *xdrs, merge *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->listA, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->listB, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
