/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "merge.h"


void
merge_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	merge  merge_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MERGE, MERGE_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	merge_1_arg.listA={'A','B','C'};
	merge_1_arg.listB={'S','P','Q'};
	result_1 = merge_1(&merge_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("[Client] Merged arrays:");
		int i=0;
		for(i=0;i<6;i++){
			printf("%d\t",result_1[i]);
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	merge_1 (host);
exit (0);
}
