/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REVERSE_H_RPCGEN
#define _REVERSE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct reverse {
	char str[10];
};
typedef struct reverse reverse;

#define REVERSE 0x25671111
#define REVERSE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define REVERSE 1
extern  int * reverse_1(reverse *, CLIENT *);
extern  int * reverse_1_svc(reverse *, struct svc_req *);
extern int reverse_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REVERSE 1
extern  int * reverse_1();
extern  int * reverse_1_svc();
extern int reverse_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_reverse (XDR *, reverse*);

#else /* K&R C */
extern bool_t xdr_reverse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REVERSE_H_RPCGEN */
