/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reverse.h"


void
reverse_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	reverse  reverse_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REVERSE, REVERSE_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	reverse_1_arg.str="Spandana";
	result_1 = reverse_1(&reverse_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("[Client] Reverse of a string:%d",result_1);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	reverse_1 (host);
exit (0);
}
