/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	add  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD, ADD_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.matrixA[2][2]={
			{2,3},
			{4,5}	};
	add_1_arg.matrixB[2][2]={
			{5,2},
			{4,5}	};
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("[Client] Addition of two matrices");
		int i=0,j=0;
		for(i=0;i<2;i++){
			for(j=0;j<2;i++){
				printf("%d\t",result_1[i][j]);
			if(j==1)
				printf("\n");
			}
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_1 (host);
exit (0);
}
